baseurl = "http://192.168.0.133"
title = "Venezuela Sostenible"
theme = "hugo-theme-cleanwhite"
languageCode = "es-ve"
# Enable comments by entering your Disqus shortname
disqusShortname = "imerualfonzo"
googleAnalytics = "imerualfonzo"
preserveTaxonomyNames = true
paginate = 10 #frontpage pagination
hasCJKLanguage = true

# Urls
#uglyURLs = "true"

[outputs]
home = ["HTML", "RSS", "Algolia"]

[taxonomies]
  category = "categories"
  tag = "tags"
  region = "regiones"


[params]
  header_image = "img/imerualfonzo-ods.webp"
  SEOTitle = "Creamos una nueva Venezuela"
  description = "Dedicado a las personas amantes de la Naturaleza, activas, este portal es una manera de llegar hasta donde siempre has querido, podemos hacer la diferencia de un mejor futuro... un nuevo estilo de vida."
  keyword = "naturaleza, ambiente, Venezuela, desarrollo sostenible, imeru alfonzo, politica, ecoturismo, geologia, democracia"
  slogan = "Construyamos... un nuevo estilo de vida"

  image_404 = "img/404-bg.webp"
  title_404 = "Llegaste a un páramo sin conocimiento :("
  omit_categories = false

  # leancloud storage for page view counter
  page_view_conter = false
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = true
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = "Movimiento, Somos exploradores, entusiastas y Defensores de la Naturaleza"
  sidebar_avatar = "img/favicon.ico"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true 
  featured_condition_size = 1 

  # Baidu Analytics
  ba_track_id = ""
  
  # We need a proxy to access Disqus api in China
  # Follow https://github.com/zhaohuabing/disqus-php-api to set up your own disqus proxy
  disqus_proxy = ""
  disqus_site = ""

# Twikoo comments
  # Follow https://twikoo.js.org/ to set up your own env_id
  twikoo_env_id = ""
  
  #Enable wechat pay & alipay to allow readers send reward money if they like the articles 
  reward = true 
  # reward_guide = "" 

  friends = true
  bookmarks = true
  about_me = true

  # Include any custom CSS and/or JS files, url or relative to /static folder
  # custom_css = ["css/lightbox.css", "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css", "css/main.css"]
  # custom_js = ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js"]

  [params.social]
  rss            = true 
  email          = "ecodefensores.venezuela@gmail.com"
  facebook      = "https://www.facebook.com/venezuelasostenible/"
  #googleplus    = "full profile url in googleplus"
  #twitter       = "https://twitter.com/imerualfonzo"
  #linkedin       = "https://www.linkedin.com/in/imerualfonzo/"
  instagram     = "https://www.instagram.com/venezuelasostenible/"
  #wechat         = "img/wechat_qrcode.jpg"
  #github         = "https://github.com/yourgithub"
  #pinterest     = "full profile url in pinterest"
  #reddit        = "full profile url in reddit"
  #mastodon      = "full profile url in mastodon"
  #keybase       = "full profile url in keybase"
  #xing          = "https://www.xing.com/profile/yourxingid"
  #git           = "full profile url for git user"
  
  [[params.friend_link]]
  title = "Imerú Alfonzo, Página personal"
  href =  "https://imerualfonzo.com"

  #[[params.bookmark_link]]
  #title =  "Martin Fowler"
  #href =  "https://martinfowler.com"
  #[[params.bookmark_link]]
  #title = "ServiceMesher"
  #href =  "http://www.servicemesher.com"
  #[[params.bookmark_link]]
  #title =  "Pxhere"
  #href = "https://pxhere.com"
  #[[params.bookmark_link]]
  #title = "unsplash"
  #href = "https://unsplash.com"
  #[[params.addtional_menus]]
  #title =  "Publicaciones"
  #href =  "/top/books/"
  [[params.addtional_menus]]
  title =  "Acerca"
  #title =  "ABOUT"
  href =  "/top/about/"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags", "regiones"] 

[markup]
  [markup.tableOfContents]
    endLevel = 3
    startLevel = 1
  [markup.highlight]
    style = "dracula"
